[project]
name = "banquinho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "DaNooXT", email = "raulkbauer2009@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dbt-core>=1.12.5",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
banquinho = "banquinho:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
